try out trivy ouput

diff --git a/.github/workflows/trivy.yml b/.github/workflows/trivy.yml
--- a/.github/workflows/trivy.yml
+++ b/.github/workflows/trivy.yml
@@ -16,7 +16,8 @@ jobs:
     runs-on: ubuntu-18.04
     steps:
       - name: Run Trivy vulnerability scanner
-        uses: tanguyseg/trivy-action@master
+        id: trivy
+        uses: tanguyseg/trivy-action@outputs
         with:
           image-ref: ${{ github.event.inputs.image }}:${{ github.event.inputs.tag }}
           format: table
@@ -24,3 +25,18 @@ jobs:
           ignore-unfixed: true
           vuln-type: os,library
           severity: CRITICAL,HIGH
+
+      # The goal here is to do something only if Trivy detected some
+      #   vulnerabilities, while keeping its exit code at 0 to prevent it from
+      #   failing if used in another composite action
+      - name: Do something if trivy found a vulnerability
+        if: ${{ steps.trivy.outputs.total }} != 0
+        run: |
+          echo Trivy found ${{ steps.trivy.outputs.total }} vulnerabilites
+          exit 1
+      - name: Do something else if trivy did not find any vulnerability
+        if: ${{ steps.trivy.outputs.total }} == 0
+        run: |
+          echo Trivy did not found any vulnerability
+
+
